sonar.organization=jhemder
sonar.projectKey=Jhemder_UPeU_Events
sonar.projectName=UPeU_Events

# Apuntamos directo al código de Flutter y sus pruebas
sonar.sources=lib
sonar.tests=test

# Tipo de codificación estándar
sonar.sourceEncoding=UTF-8

# Excluir archivos generados (muy importante en Flutter para evitar errores)
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,lib/generated_plugin_registrant.dart